
#配置数据源的属性
spring:
#redis的配置
  redis:
    host: 47.113.193.76
    port: 6379
    password: 123456
    jedis:
      pool:
        max-idle: 20
        max-active: 25
        min-idle: 10
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/0520erp?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
      username: root
      password: root123
      max-active: 20
      max-wait: 5000
      initial-size: 1
      filters: stat,log4j,wall
      validationQuery: SELECT 'x'   #验证连接
      enable: true
   #监控配置
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 123456
        allow: 
        deny: 
        url-pattern: /druid/*
  #thymeleaf的配置 
  thymeleaf: 
    cache: false
    enabled: true
#      web-stat-filter: 
#        enabled: true
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  activiti:
    database-schema-update: true
    history-level: full
    check-process-definitions: true
    process-definition-location-prefix: classpath:/processes/

# token配置
#token:
#    # 令牌自定义标识
#    header: Authorization
#    # 令牌密钥
#    secret: abcdefghijklmnopqrstuvwxyz
#    # 令牌有效期（默认30分钟）
#    expireTime: 30
#关闭activiti自动部署（使用流程设计器部署，不使用具体文件访问方式）

#  false：false为默认值，设置为该值后，Activiti在启动时，会对比数据库表中保存的版本，如果版本不匹配时，将在启动时抛出异常。
#  true：设置为该值后，Activiti会对数据库中所有的表进行更新，如果表不存在，则Activiti会自动创建。
#  create-drop：Activiti启动时，会执行数据库表的创建操作，在Activiti关闭时，执行数据库表的删除操作。
#  drop-create：Activiti启动时，执行数据库表的删除操作在Activiti关闭时，会执行数据库表的创建操作。

#  none：不保存任何的历史数据，因此，在流程执行过程中，这是最高效的。
#  activity：级别高于none，保存流程实例与流程行为，其他数据不保存。
#  audit：除activity级别会保存的数据外，还会保存全部的流程任务及其属性。audit为history的默认值。
#  full：保存历史数据的最高级别，除了会保存audit级别的数据外，还会保存其他全部流程相关的细节数据，包括一些流程参数等。
#配置mybatisplus
mybatis-plus:
  mapper-locations:
  - classpath:mapper/*/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
    banner: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    
#shiro的配置
shiro:
  hash-algorithm-name: md5
  hash-iterations: 2
  anon-urls:
    - /index.html*
    - /sys/toLogin*
    - /login/login*
    - /resources/**
  login-url: /index.html
  log-out-url: /login/logout*
  authc-ulrs:
    - /**
server:
  port: 9494
